nss-day-cohort-54/c54-Rare-PP-client

src/components/ApplicationViews.js, src/components/allposts/AllPosts.js, src/components/createposts/CreatePosts.js, src/components/home/Home.js, src/components/nav/NavBar.js
=> added navbar functionality and preliminary routing

src/components/categories/AllCategories.js, src/components/categories/CategoryManager.js
Added categories component and added AllCategories.js and CategoryManager.js files within the component.
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
=> added category component and files

src/components/tags/CreateTagForm.js
added comments
no testing needed
=> Hwh create tag comments

src/components/nav/NavBar.js, src/components/posts/AllPosts.js, src/components/posts/CreatePosts.js, src/components/posts/PostManager.js
Added content, category, author, and date to be rendered to DOM
- Breaking change (still need category_requests.py on server side to be coded)
=> Mcm algorithm writing

src/components/categories/CreateCategoryForm.js
added file CreateCategoryForm under categories, commented algorithm, no testing needed
no testing necessary 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
=> commented algorithm for create category form

src/components/posts/CreatePosts.js
just comments no testing needed
=> add tags to post comments

src/components/nav/NavBar.js
Nav bar items were being duplicated. Removed duplicate code.
- Bug fix (non-breaking change which fixes an issue)
=> Fixed nav bar duplication

src/components/posts/AllPosts.js
On all posts view.
Error with getting and displaying the data from the server. post.user was an object but directly paced in JSX resulting in error.
Changed to post.user.first_name for now.
- Bug fix (non-breaking change which fixes an issue)
=> Fixed post view issue

src/components/ApplicationViews.js, src/components/nav/NavBar.js, src/components/users/UserList.js
Changed "home" view url to conform to issue decscriptions
"/" instead of "/home"
Added /users view and Users link in navbar
=> Jdc change home

src/components/ApplicationViews.js, src/components/tags/AllTags.js, src/components/tags/TagManager.js
When you click tag manager in the nav bar, all tags will be displayed, in alphabetical order
issue 48
=> tags displaying

src/components/users/User.css, src/components/users/User.js, src/components/users/UserList.js, src/components/users/UserManager.js, src/components/utils/Settings.js
On Users view should generate table of all users
- username
- first name
- last name
- email
=> Jdc generate user list

src/components/tags/AllTags.js
added edit and delete buttons for each tag
- Bug fix (non-breaking change which fixes an issue)
go to the tag manager page and verify that there is a non functioning edit and delete button for each tag
=> edit and delete buttons added

src/components/tags/AllTags.js, src/components/tags/CreateTagForm.js
Added in the create new tag form and functionality for it
=> add new tag form working

src/components/ApplicationViews.js, src/components/categories/AllCategories.js, src/components/categories/CategoryManager.js
Added functionality to AllCategories file, user should be routed to AllCategories page when Category Manager is clicked on the nav bar.
=> Orl viewing categories

src/components/users/SubForm.js, src/components/users/SubManager.js, src/components/users/User.js, src/components/utils/Fetch.js, src/index.css
Added subscribe/unsubscribe button
=> Added subscribe button

src/components/home/Home.js, src/components/posts/SubbedPosts.js
=> Added getting posts from author user is subbed to

src/components/ApplicationViews.js, src/components/posts/AllPosts.js, src/components/posts/MyPosts.js, src/components/posts/Post.css, src/components/posts/Post.js, src/components/posts/PostManager.js, src/components/posts/PostsByUser.js, src/components/posts/SinglePost.js, src/components/posts/SubbedPosts.js, src/components/users/User.js
Added view post details views, incld. css.
Card Format details
On All Posts /posts/all
On My Posts /posts/myPosts
On Home "/"
On Posts by author /users/{userId}
On Single Post /posts/single/{postId}
=> added post details views

src/components/posts/AllPosts.js, src/components/posts/PostManager.js
Added fetch to PostManager to search posts by title
Added fieldset with text input and search button
- This change requires a documentation update
=> Mcm search post by title

src/components/categories/AllCategories.js, src/components/categories/CreateCategoryForm.js
When user is on the Category page, user should be able to submit a new category.
=> Orl create category form

src/components/ApplicationViews.js, src/components/nav/NavBar.js, src/components/posts/CreatePosts.js
added create new post functionality
=> Hwh create post

src/components/posts/AllPosts.js
Added logic for multiple filtering options. No current functionality change.
=> Jdc filter comments

src/components/posts/CreatePosts.js
=> adding tags to post working

src/components/ApplicationViews.js, src/components/comments/Comment.js, src/components/comments/CommentForm.js, src/components/comments/CommentManager.js, src/components/comments/CommentsList.js, src/components/posts/Post.js
Added ability to see, add, and delete comments.
=> Added comments functionality

src/components/ApplicationViews.js, src/components/posts/CreatePosts.js, src/components/posts/Post.js
Added functionality for editing post including tags
Currently editing is only found through a single post page. More links to get to editing a post to be added later.
=> added editing post functionality

src/components/buttonControls/ButtonControls.js, src/components/comments/Comment.js, src/components/posts/AllPosts.js, src/components/posts/CreatePosts.js, src/components/posts/MyPosts.js, src/components/posts/Post.js, src/components/posts/PostManager.js
=> Mcm buttons
